export const ADD_TODO = 'todos/todoAdded'
export const TOGGLE_TODO = 'todos/todoToggled'
export const SELECT_COLOR = 'colorSelected'
export const DELETE_TODO = 'todos/todoDeleted'
export const COMPLETE_ALL = 'todos/allCompleted'
export const CLEAR_ALL = 'todos/completedCleared'
export const CHANGE_FILTER_STATUS = 'filters/statusFilterChanged'
export const CHANGE_COLOR_FILTER = 'filters/colorFilterChanged'
